#!/usr/bin/env bash
set -euo pipefail

export PRETRAINED_MODEL_NAME_OR_PATH="${PRETRAINED_MODEL_NAME_OR_PATH:-yisol/IDM-VTON}"
export PRETRAINED_GARMENTNET_PATH="${PRETRAINED_GARMENTNET_PATH:-yisol/IDM-VTON}"
export PRETRAINED_GARMENTNET_SUBFOLDER="${PRETRAINED_GARMENTNET_SUBFOLDER:-unet_encoder}"
export PRETRAINED_IP_ADAPTER_PATH="${PRETRAINED_IP_ADAPTER_PATH:-skip}"
export IMAGE_ENCODER_PATH="${IMAGE_ENCODER_PATH:-yisol/IDM-VTON}"
export IMAGE_ENCODER_SUBFOLDER="${IMAGE_ENCODER_SUBFOLDER:-image_encoder}"

export DATASET_ROOT="${DATASET_ROOT:-/workspace/DressCode_IDM_Train_2K}"
export CATEGORY="${CATEGORY:-upper_body}"
export OUTPUT_DIR="${OUTPUT_DIR:-/workspace/idm_outputs/official_upper_2k_lr1e-6_steps500}"

export HEIGHT="${HEIGHT:-1024}"
export WIDTH="${WIDTH:-768}"
export TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-1}"
export TEST_BATCH_SIZE="${TEST_BATCH_SIZE:-1}"
export GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-1}"
export MAX_TRAIN_STEPS="${MAX_TRAIN_STEPS:-500}"
export CHECKPOINTING_STEPS="${CHECKPOINTING_STEPS:-500}"
export LOGGING_STEPS="${LOGGING_STEPS:-20}"
export VALIDATION_STEPS="${VALIDATION_STEPS:-500}"
export VALIDATION_SAMPLES="${VALIDATION_SAMPLES:-1}"
export LEARNING_RATE="${LEARNING_RATE:-1e-6}"
export DISABLE_VALIDATION="${DISABLE_VALIDATION:-1}"
export USE_8BIT_ADAM="${USE_8BIT_ADAM:-1}"

bash /workspace/run-idm-dc-train.sh
